### ISSUE TITLE
[INVALID] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [bartobri/mrrcrypt#1]
Dear Brian,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows, if possible?

**Comment by bartobri** [comment]
Hello.

I don't think this program will run on windows without some kind of emulated linux environment. You may want to try installing cygwin and then following the installation instructions for mrrcrypt. I do not have windows myself to test with.

Thanks,
Brian

**Comment by sergeevabc** [comment]
Thank you for letting me know, Brian.
Oh, had a mere user like me been able to compile in the first place, he would be called a developer.
