### ISSUE TITLE
Weak key existence

### ISSUE THREAD

**Issue by skeeto** [bartobri/mrrcrypt#2]
This is a neat project. I wanted to subject it to a more aggressive entropy test by choosing a less ideal key. So I made this change:

```diff
diff --git a/src/modules/keyfile.c b/src/modules/keyfile.c
index 0a9f036..edea763 100644
--- a/src/modules/keyfile.c
+++ b/src/modules/keyfile.c
@@ -133,7 +133,7 @@ int keyfile_create(char *keyFileFullPathName) {
 		return 0;
 		
 	// Open the urandom resource
-	if ((urandom = fopen("/dev/urandom", "r")) == NULL)
+	if ((urandom = fopen("/dev/zero", "r")) == NULL)
 		return 0;
 
 	// Write mirror data to file
```

This forces it to generate a "zero" key. Then I used this key to encrypt a stream of zeros, piping the result into dieharder:

    mrrcrypt </dev/zero | dieharder -g200 -a > results.txt

Here it is: [results.txt](https://github.com/bartobri/mrrcrypt/files/1721338/results.txt). It fails over 75% of the tests, proving there's at least one weak key. I imagine this is not the only weak key, and feeding other low-entropy patterns to the key generator would probably uncover more.

I'm not suggesting you necessarily change anything. I just thought this was an interesting result.

**Comment by bartobri** [comment]
This change basically generates an empty mirror field, which reduces the utility to something barely better than a basic cracker-jack cypher. I've played around a lot with determining what the optimal mirror field density is. This algorithm seems to work best with a field where 1 out of every 10 positions contains a mirror. Any more or less tends to degrade the encryption strength. Your change reduces the mirror density to literally zero, so it is not a surprise that it performs poorly in tests.

Nonetheless, thanks for the interest in my project. Let me know if you think it has any redeeming qualities that would be worth further development.

- Brian
